<!------------------------------------------------------------------------------------------------->
# Series de tiempo

<!------------------------------------------------------------------------------------------------->
## Distribuciones de conteo, discretas

::: {.definition #dbinom name="Distribución binomial"}
Una variable aleatoria $N$ que toma valores en $\mathbb{N}$ se dice que sigue una distribución 
o ley de binomial $N \rightsquigarrow Bin( n, p )$, con parámetros $n \in \mathbb{N}$ y 
$p \in [0, 1]$, si:
\begin{equation}
P( N = k ) = \binom{n}{k} p^k ( 1 - p )^{n-k}, \qquad
\forall k \in \{0,\ldots, n\}
\end{equation}
:::
En R se puede para trabajar con variables aleatorias de binomiales se puede utilizar las siguientes
funciones

::: {.definition #dpois name="Distribución de Poisson"}
Una variable aleatoria $N$ que toma valores en $\mathbb{N}$ se dice que sigue una distribución 
o ley de Poisson $N \rightsquigarrow Pois( n, p )$, con parámetro $\lambda \in \mathbb{R}$, si:
\begin{equation}
P( N = k ) = e^{-\lambda} \frac{\lambda^k}{k!}, \qquad
\forall k \in \mathbb{N}
\end{equation}
:::
```{r l4c2}
lambda <- 2
n <- 10
k <- 2
N <- rpois( n = n, lambda = lambda ) # simular una muestra de tamaño n, N sigue Pois( lambda )
pk <- dpois( k, lambda = lambda ) # cálculo de probabilidad P( N = k )
Pk <- ppois( k, lambda = lambda ) # cálculo de probabilidad P( N <= k )
```

::: {.definition #dnbinom name="Distribución binomial negativa"}
Una variable aleatoria $N$ que toma valores en $\mathbb{N}$ se dice que sigue una distribución 
o ley de  binomial negativa $N \rightsquigarrow NBin( \alpha, p )$, con parámetro $\alpha > 0$ y 
$p \in (0,1)$, si:
\begin{equation}
P( N = k ) = \binom{\alpha + k - 1}{k} p^\alpha ( 1 - p )^k
= \frac{\Gamma( \alpha + k )}{\Gamma(k+1) \Gamma(\alpha)}p^\alpha ( 1 - p )^k, \qquad
\forall k \in \mathbb{N}
\end{equation}
donde $\Gamma( \alpha ) = \int\limits_0^{+\infty} x^{\alpha - 1} e^{-x}\ dx$, $\forall \alpha \geq 0$
:::

Asociado a estas distribuciones discretas existe un resultado de caracterización, el cual permite
seleccionar la distribución de conteo.

<!------------------------------------------------------------------------------------------------->
## Distribuciones continuas

::: {.definition #dunif name="Distribución uniforme"}
Una variable aleatoria $X$ a valores reales, sigue una distribución uniforme 
$X \rightsquigarrow Unif( a, b )$ de parámetros $a, b \in \mathbb{R}$, si su función de distribución
acumulada es de la siguiente forma:
\begin{equation}
F_X( x ) = \frac{x-a}{b-a} \mathbf{1}_{[a,b)}( x ) + \mathbf{1}_{[b,+\infty)}( x )
\end{equation}
sin mucho esfuerzo se puede verificar que su densidad de probabilidad está dada por la función
\begin{equation}
f_X( x ) = \frac{1}{b-a}\mathbf{1}_{[a,b]}( x )
\end{equation}
:::

::: {.definition #dexp name="Distribución exponencial"}
Una variable aleatoria $X$ a valores reales, sigue una distribución exponencial 
$X \rightsquigarrow Exp( \lambda )$ de parámetros $\lambda > 0$, si su función de distribución
acumulada es de la siguiente forma:
\begin{equation}
F_X( x ) = \mathbf{1}_{(0,+\infty)}( x ) \left( 1 - e^{-\lambda x} \right)
\end{equation}
sin mucho esfuerzo se puede verificar que su densidad de probabilidad está dada por la función
\begin{equation}
f_X( x ) = \mathbf{1}_{(0,+\infty)}( x ) \lambda e^{-\lambda x}
\end{equation}
:::

::: {.definition #dnorm name="Distribución normal"}
Una variable aleatoria $X$ a valores reales, sigue una distribución normal 
$X \rightsquigarrow N( \mu, \sigma )$ de parámetros $\mu \in \mathbb{R}$, $\sigma > 0$, si su 
función de distribución acumulada es de la siguiente forma:
\begin{equation}
F_X( x ) = \frac{1}{\sqrt{2\pi} \sigma} \int\limits_{-\infty}^x e^{-\frac{(y - \mu)^2}{\sigma^2}}\ dy
\end{equation}
la densidad de probabilidad automáticamente está dada por la función:
\begin{equation}
f_X( x ) = \frac{1}{\sqrt{2\pi}} e^{-\frac{(x - \mu)^2}{\sigma^2}}
\end{equation}
:::

::: {.definition #dlnorm name="Distribución log-normal"}
Una variable aleatoria $X$ a valores reales, sigue una distribución log-normal 
$X \rightsquigarrow LN( \mu, \sigma )$ de parámetros $\mu > 0$, $\sigma > 0$, si su 
función de distribución acumulada es de la siguiente forma:
\begin{equation}
F_X( x ) = \frac{1}{\sqrt{2\pi} \sigma} \int\limits_{0}^{\ln(x)} e^{-\frac{(y - \mu)^2}{\sigma^2}}\ dy
\end{equation}
la densidad de probabilidad automáticamente está dada por la función:
\begin{equation}
f_X( x ) = \frac{1}{\sqrt{2\pi}} e^{-\frac{(\ln(x) - \mu)^2}{\sigma^2}}
\end{equation}
:::
En pocas, una variable aleatoria $X \rightsquigarrow LN( \mu, \sigma )$ sigue una distribución 
log-normal si y solamente si la variable aleatoria dada por su logaritmo $\ln( X ) \rightsquigarrow N( \mu, \sigma )$ 
sigue una distribución normal.

::: {.definition #dlnorm name="Distribución de Pareto generalizada"}
Una variable aleatoria $X$ a valores reales, sigue una distribución de Pareto generalizada
$X \rightsquigarrow GPD( \mu, \sigma, \xi )$ de parámetros $\mu \in \mathbb{R}$, $\sigma > 0$, 
$\xi \in \mathbb{R}$, si su función de distribución acumulada es de la siguiente forma:
\begin{equation}
F_X( x ) = 
\left\{
\begin{array}{ll}
1 - \left( 1 + \xi \frac{x - \mu}{\sigma} \right)^{-\frac{1}{\xi}} & \text{si}\ \xi \neq 0 \\
1 - e^{-\frac{x-\mu}{\sigma}} & \text{si}\ \xi = 0 \\
\end{array}
\right.
\end{equation}
la densidad de probabilidad está dada por la función:
\begin{equation}
f_X( x ) = \frac{1}{\sigma} \left( 1 + \xi \frac{x - \mu}{\sigma} \right)^{-1-\frac{1}{\xi}}
\end{equation}
:::


<!------------------------------------------------------------------------------------------------->
## Familia de Panjer

::: {.definition #fampanjer name="Familia de Panjer"}
Una variable aleatoria discreta $N$, que toma valores enteros positivos $N \in \mathbb{N}$, se dice
que pertenece a la **familia de Panjer**, si sus probabilidades $p_k = P( N = k )$ para cada 
$k \in \mathbb{N}$, satisfacen la siguiente relación de recurrencia.
\begin{equation}
p_k = \left( a + \frac{b}{k} \right)p_{k-1},\qquad \forall k \in \mathbb{N} \setminus \{0\} 
\end{equation}
:::

Además tenemos la siguiente proposición que caracteriza a la distribución de las variables 
aleatorias en la familia de Panjer.

::: {.proposition #chfampanjer name="Caracterización familia de Panjer"}
Las únicas leyes de probabilidad que satisfacen la relación de recurrencia anterior son:

1. La ley de Poisson, la cual se obtiene para $a = 0$ y $b > 0$

2. La ley binomial negativa, la cual se obtiene para $0 < a < 1$ y $a + b > 0$

3. La ley binomial, la cual se obtenida para $a < 0$ y $b = -a(m + 1)$, para cierto $m$ entero y 
positivo.
:::

Para una demostración detallada de la proposición anterior se puede consultar @MathAssuNV1 o 
en https://nonlifemaths.github.io/.