<!------------------------------------------------------------------------------------------------->
# Reservas técnicas

<!------------------------------------------------------------------------------------------------->
## Reservas para primas no adquiridas

<!------------------------------------------------------------------------------------------------->
## Reservas de riesgos en curso

Esta reserva corresponde a la cantidad restante prima que debería ser prorrateada en el tiempo para 
cubrir de forma uniforme los reclamos de cada póliza hasta su fecha término.

En otras palabras si tenemos una cantidad de pólizas vendidas $n$, para cada póliza 
$i \in \{1, \ldots, n \}$, le corresponde un una duración $D_i = \left[ T^1_i,  T^2_i \right]$, con $T^1_i > 0$ 
el tiempo inicial de la vigencia de la póliza, $T^2_i > T^1_i$ el tiempo final de vigencia de la 
póliza y una prima pagada por la cobertura adquirida $\Pi_i$ para la $i$-ésima póliza. 

Así, la forma más sencilla de calcular la reserva de riesgo en curso $RRC$ en el tiempo $t$, está 
dada por:
$$
RRC( t ) = \sum\limits_{i=1}^n \mathbf{1}_{\left[T^1_i, T^2_i\right]}( t ) \frac{T^2_i - t}{T^2_i - T^1_i} \Pi_i 
$$

Esta metodología es la más sencilla, pero no toma en cuenta que no siempre sucede que los reclamos 
son proporcionales a la cantidad de prima restante en el tiempo. Incluso en el caso que el valor
de los reclamos sea proporcional al tiempo restante, no necesariamente será uniformemente 
proporcional al tiempo restante de cobertura. Esto puede llevar a manera niveles de reservas de 
primas no óptimos acorde a las operaciones del asegurador.

La cantidad de prima que va quedando a favor del asegurador y de la cual en teoría este puede 
disponer está dada por la **prima devengada** $PDG$:
$$
PDG( t ) = \sum\limits_{i=1}^n \mathbf{1}_{\left[T^1_i, +\infty\right)}( t ) 
\frac{\min\left( t, T^2_i \right) - T^1_i}{T^2_i - T^1_i} \Pi_i 
$$

En algunas situaciones se suele considerar tener reserva de primas por el mismo valor constante 
a los largo de la duración de la póliza. Usualmente esto se lo suele hacer para los productos de 
corto plazo con duraciones menores de un año. Así se suele dividir el conjunto de pólizas 
$\{1,\ldots,n\} = I \cup J$ en dos conjuntos disjuntos, donde $I$ contiene a las pólizas para las 
cuales se reserva proporcionalmente al tiempo y la prima y $J$ contiene aquellas pólizas para las 
cuales se mantiene la reserva constante por toda la duración de la póliza.
$$
RRC( t ) = \sum\limits_{i \in I} \mathbf{1}_{D_i}( t ) \frac{T^2_i - t}{T^2_i - T^1_i} \Pi_i 
+ \sum\limits_{i \in J} \mathbf{1}_{D_i}( t ) \Pi_i 
$$
de ingual manera la prima devengada $PGD$ está dada por:
$$
PDG( t ) = \sum\limits_{i \in I} \mathbf{1}_{\left[T^1_i, +\infty\right)}( t ) 
\frac{\min\left( t, T^2_i \right) - T^1_i}{T^2_i - T^1_i} \Pi_i 
+ \sum\limits_{i \in J} \mathbf{1}_{\left(T^2_i,+\infty\right)}( t ) \Pi_i 
$$


<!------------------------------------------------------------------------------------------------->
## Reservas de siniestros a pagar

1. $T$

<!------------------------------------------------------------------------------------------------->
### Siniestros sucedidos, reportados, resueltos, no pagados
  
<!------------------------------------------------------------------------------------------------->
### Siniestros sucedidos, reportados, no resueltos, no pagados
$$

$$
  
<!------------------------------------------------------------------------------------------------->
### Siniestros sucedidos, no reportados, no resueltos, no pagados

$$
IBNR
$$
