<!------------------------------------------------------------------------------------------------->
# Introducción a las operaciones de seguros {#introduccion_operaciones_seguros}

<!------------------------------------------------------------------------------------------------->
## El sistema financiero

En todos lo países del mundo existe un sistema financiero con el objetivo de ofrecer facilidades 
para poner en práctica las decisiones financieras de:

- Personas
- Empresas
- Gobierno.

En general en un sistema financiero encontramos: 

- Mercados de activos financieros
  - Deuda, Derivados, Títulos…
- Intermediarios (públicos y privados)
  - Bancos
  - Empresas de seguros
  - Fondos de pensiones
- Empresas de servicios
  - Difusión de información
  - Tarjetas de crédito, *brokers*…
  

Por medio de las instituciones del sistema, se espera facilitar algunas operaciones:

- Transferencia de recursos
- A través del tiempo, regiones, entre, industrias,…
- Administración del riesgo
- Medios para administrar el riesgo financiero
- Compensación y establecimiento de pagos
- Facilitar el intercambio de bienes,servicios, activos…
- Concentración de recursos
- Financiamiento de grandes empresas y proyectos
- Suministro de información
- Toma de decisiones en iguales condiciones

<!------------------------------------------------------------------------------------------------->
## Riesgos financieros

Los riegos financieros son aquellos riesgos relacionados con las posibles pérdidas económicas que
pueden enfrentar los actores del sistema (personas, empresas, gobierno), causadas por hechos 
contingentes que amenazan sus operaciones en el mercado financiero, sus actividades de negocio 
o sus pertenencias (activos financieros).

De manera natural los individuos presentan un comportamiento que traduce su "miedo" a las pérdidas 
cuando enfrentan situaciones de riesgo: la **aversión al riesgo**. 

La aversión al riesgo se produce hacia la parte negativa del riesgo, esto es ante la posibilidad de 
pérdidas financieras.

En estas situaciones es necesario administrar el riesgo, para lo cual co-existen cuatro formas 
principales:

1. Evitar el riesgo (no siempre posible)
2. Prevenir y controlar el riesgo
3. Aceptar el riesgo
4. Transferir el riesgo

Vale recordar que históricamente los grandes avances de la humanidad han sido posibles gracias a
a la aceptación y correcta gestión de de riesgos muy importantes. 

Por lo tanto, en lugar de evitar los riesgos debemos tratar de conocerlos profundamente para 
aceptarlos y poder aprovechar las oportunidades que brinda su correcta gestión.

:::: {.ideabox data-latex=""}
**Para pensar:**

*El riesgo existe gracias a nuestra humana
incapacidad de conocer el futuro, a nuestras
limitaciones para identificar sus verdaderas
causas. Y mientras así sea, debemos
esforzarnos por comprenderlo, aceptarlo y
gestionarlo inteligentemente y con humildad.*

-- L. Vélez, 2003
::::

<!------------------------------------------------------------------------------------------------->
## Los seguros y la transferencia de riesgos financieros

Transferir el riesgo consiste en trasladar el riesgo a otros a un costo razonable. Esto es posible 
en un sistema financiero gracias a mecanismos como:

- **Protección:** reducir una pérdida potencial a costa de renunciar a una ganancia.
- **Diversificación:** distribuir una pérdida potencial en varias pérdidas menores con distintas 
exposiciones al riesgo.
- **Aseguramiento:**  pagar una prima para compensar una pérdida potencial mayor.

El aseguramiento consiste en transferir a una compañía de seguros, la totalidad o parte de las 
posibles pérdidas financieras que enfrenta un asegurado, bajo las condiciones estipuladas en un 
contrato: la *póliza de seguro*.

En la práctica, el seguro permite al asegurado reducir significativamente el impacto 
del riesgo en su patrimonio, pero no eliminarlo por completo. Entonces, una operación de seguro 
consiste en sustituir un riesgo inicial por otro más ventajoso para el asegurado, a cambio del pago 
de una prima.

Además es necesario tomar en cuenta que el asegurado también asume el riesgo de quiebra de la 
aseguradora, en cuyo caso la compañía no podrá brindar la cobertura ofrecida por los daños sufridos 
por el asegurado.

<!------------------------------------------------------------------------------------------------->
## La mutualización de riesgos

La técnica fundamental de la industria de seguros es **la mutualización o compensación de riesgos**: 
muchos peligros (accidentes, robos, enfermedades, etc.) amenazan a un gran número de personas, pero 
a la final afectan solo a un número reducido de personas. 

Por lo tanto, el seguro aprovecha esta técnica para financiar el pago de pocos siniestros por medio de 
las primas recolectadas de muchos asegurados a un mismo riesgo y para hacer de esto un negocio lucrativo.

En este contexto, para que la mutualización de riesgos funciones es necesario que los riesgos estén 
suficientemente **dispersos** y guarden entre ellos un cierto grado de **independencia**.

Ilustremos estos conceptos con un simple análisis:

- Si la compañía emitiera una sola póliza (que cubriera incendios, por ejemplo), obtendría un 
beneficio modesto con una alta probabilidad (si el incendio no destruye la propiedad asegurada), 
pero estaría expuesta a una pérdida considerable si se produjera un siniestro. En este caso, la 
situación de la compañía es idéntica a la del asegurado!. 

- Si, por el contrario, la compañía suscribe un gran número de pólizas contra incendios, que cubren 
edificaciones similares, y si un siniestro que afecta a una de las pólizas no influye en los demás 
riesgos de la cartera, intuitivamente vemos que que la compañía podría 
*mutualizar o compensar los riesgos*, es decir, financiar el pago de las pérdidas que afectan a un 
pequeño número de pólizas, utilizando las primas recolectadas de todas las pólizas de la cartera. 

- En resumen, hablamos de mutualización de riesgos cuando la aseguradora logra agrupar en su cartera 
un gran número de riesgos similares (dispersión) y sin influencia mutua (independencia), y de esta 
forma puede utilizar las primas de todos los contratos para compensar y financiar los reclamos por 
los siniestros sufridos por los asegurados desafortunados...

- ... y además obtiene una ganancia!


Pero ¿hasta qué punto podemos mutualizar los riesgos?

Existen casos como los riesgos catastróficos o de desastres naturales que no pueden ser mutualizados.

En efecto, los riesgos catastróficos o de desastres naturales (ej. terremotos), son riesgos que no 
están suficientemente dispersos y afectan a un gran número de asegurados al mismo tiempo, por lo cual
escapan al principio de mutualización o compensación. 

Tradicionalmente, los riesgos catastróficos estaban excluidos del seguro, pero hoy en día, su 
asegurabilidad tiene una creciente aceptación gracias a las operaciones de **coaseguro** y 
**reaseguro** que se utilizan para garantizar una mayor dispersión de los riesgos, incluso a nivel 
mundial, y hacen posible la cobertura de riesgos catastróficos. 


### Perspectivas {-}

En mercados más desarrollados, existen otras técnicas poco utilizadas en nuestro mercado local, 
que ofrecen soluciones en algunos casos donde la técnica de mutualización podría fallar:

- La **titularización de riesgos**: permite a las compañías de seguros recurrir al mercado financiero 
para cubrir los riesgos que han suscrito.

- De manera más general, las técnicas denominadas **transferencia alternativa de riesgos** podrían 
permitir realizar importantes avances en este ámbito, ampliando los límites de la asegurabilidad,
pero demandan cambios significativos en el plano legal.

- Las empresas de **retrocesión** intervienen también a nivel global como aseguradores de los 
reaseguradores.

- Empresas **captivas de seguros**: son empresas de seguros o reaseguros que son propiedad de 
otra organización generalmente no aseguradora ni reaseguradora, creadas con el objetivo de asegurar 
total o parcialmente los riesgos de su empresa matriz o grupo empresarial. Son una forma de 
autoseguro o transferencia de riesgos, que permiten a la empresa matriz, gestionar sus riesgos de 
manera más eficiente y personalizada y con costos más bajos. 

<!------------------------------------------------------------------------------------------------->
## Fundamentos técnicos de los seguros

Desde su concepción, la idea de la mutualización de riesgos que fundementa el seguro, despertó la 
necesidad de **medir** ¿cuántos son y cuánto costarán los '*pocos siniestros*' que deberá pagar un seguro?, 
y por ende, cuantificar '*cuál es el monto de la prima*' que debería recolectar de la cartera de asegurados.

Existen dos disciplinas que se ocupan del estudio de estos problemas: la *estadística* y la 
*teoría de probabilidades*. 

Ambas ramas estudian la forma de medir o cuantificar la incertidumbre, en base de una nueva magnitud:
la **probabilidad**, que es un número que expresa, *a priori*, el nivel de las posibilidades de que 
un hecho ocurra.

La estadística busca asignar una medida de probabilidad a los eventos aleatorios sobre la base de la 
observación o experimentación de esos eventos.

En cambio, la teoría de probabilidades supone que la medida de la probabilidad asociada a los eventos 
aleatorios o es conocida o se puede calcular de forma deductiva por medio del razonamiento lógico.

El objetivo principal del cálculo de probabilidades es proporcionar un método científico para 
cuantificar la probabilidad de que ocurran ciertos eventos. En este contexto, surge de forma natural 
el concepto de *variable aleatoria*, que para el actuario principalmente puede representar:

- el coste de un siniestro: *severidad*
- o el número de siniestros: *frecuencia*. 

Las variables aleatorias constituyen la herramienta esencial para modelar la transferencia y 
mutualización de riesgos entre asegurados y aseguradoras. 


### Un poco de historia...


El sustento científico de los fundamentos del seguro comenzó con los grandes desarrollos de la 
estadística y cálculo de probabilidades:

- Correspondencia entre Pascal, Caballero de Méré y Fermat sobre problemas de apuestas
  - se consideran los documentos que desencadenaron el desarrollo de la estadística y la teoría de 
  probabilidades
- Ley de los grandes números (Teorema de Bernoulli, s.XVIII y Poisson s.XIX) y
- Desarrollo del cálculo de probabilidades (Kolmogorov, s.XX).

El seguro comienza entonces a fundamentarse en las probabilidades y leyes estadísticas (en sus 
inicios el seguro fue confundido con un juego de apuestas) que posteriormente dieron nacimiento a 
una nueva disciplina: el *cálculo actuarial*, que demanda el **análisis de información histórica** 
para medir los riesgos y determinar los niveles de primas que permiten financiar las operaciones de 
seguros, considerando todos los aspectos del negocio: leyes, contabilidad, finanzas, demografía, etc.

Retomando el tema de los límites de la mutualización de riesgos, en la actualidad, las compañías de
seguros ofrecen coberturas que presentan ciertas limitaciones técnicas, pues no se basan en análisis 
de información histórica, porque ésta no existe o es limitada:

- Seguros “especiales” o “exóticos”
  - Seguro de las piernas de futbolistas, bailarinas…
  - Seguro de satélites
- Seguros nuevos
  - Ej. SPPAT (antiguo SOAT) al inicio!

En estos casos el fundamento técnico resulta subjetivo, basado en análisis de grupos de expertos que
estudian los riesgos potenciales o experiencias relacionadas que permiten determinar primas: todo
depende del nivel de la aversión al riesgo de los accionistas para aceptar los riesgos y de la 
capacidad económica de la empresa para aceptar esos negocios.

En estos casos es imprescindible el proceso de monitoreo de la evolución del riesgo.


<!------------------------------------------------------------------------------------------------->
## Ley de los grandes números

Como hemos dicho, la mutualización de riesgos no funciona con pocos asegurados, y funciona mejor 
cuanto más grande sea el número de asegurados. 

Para medir este hecho el seguro se sustenta en una de las leyes más importantes de la 
*teoría de probabilidades*:

:::: {.ideabox data-latex=""}
**Ley de los grandes números**

Las frecuencias relativas (% de ocurrencia) del resultado de un experimento aleatorio, tienden a 
estabilizarse en un valor cuando el número de experimentos es grande. Ese número es una aproximación 
de la *probabilidad de ese resultado*.
:::::


Más adelante volveremos a revisar este tema desde un punto de vista más formal.

<!------------------------------------------------------------------------------------------------->
## Microeconomía del negocio de seguros

El seguro es un **negocio** de libre competencia y con fines de lucro.

### Ciclo de producción 

En el negocio del seguro se produce el fenómeno conocido como **inversión del ciclo de 
producción**:

- El asegurador fija el precio antes de conocer el costo del producto y por lo tanto asume 
obligaciones frente a los asegurados.

- Como consecuencias las compañías de seguros captan dinero del público y por esta razón:
- Deben conformar reservas técnicas
- Son controladas por organismos de control estatal.

### Reservas técnicas

El asegurador no puede disponer inmediatamente de las primas que recibe.

Debe constituir reservas o provisiones técnicas con la finalidad de mantener niveles mínimos de
solvencia al cierre de cada ejercicio y garantizar el cumplimiento de las obligaciones financieras
que deberá honrar en el futuro por la cobertura de siniestros.

-- Ref. Norma de reservas técnicas

Una gran parte de las primas que percibe la compañía de seguros se registran en el pasivo del balance,
en calidad de reservas y representan las obligaciones futuras del asegurador con los asegurados:

- Contablemente un gran parte de las primas se registran en el pasivo y conforme se devengan pasan a 
constituir los ingresos financieros dela compañía.

- Las reservas se respaldan por las inversiones que obligatoriamente debe realiza la compañía y 
registrar en el activo del balance.

El principal riesgo del asegurador está en su pasivo.


### Control estatal

La inversión del ciclo de producción implica que los asegurados corren el riesgo de quiebra asegurador 
y éste no pueda cumplir con sus obligaciones de cubrir los siniestros en el futuro:

- Esto se conoce como riesgo de insolvencia del asegurador

Por esta razón los gobiernos han instituido la *supervisión de las compañías de seguros* a través 
de entidades de control cuyo objetivo es proteger a los asegurados, garantizando la solvencia del 
mercado asegurador en el largo plazo:

- Superintendencia de Compañías, Valores y Seguros (SCVS)
  - Leyes 
  - Normas de solvencia, nacionales e internacionales
  - Ej.: resoluciones de la SCVS, Solvencia I y II
- Otras instituciones de control
  - Junta de Política y Regulación Financiera (JPRF)

En consecuencia las compañías de seguros son compañías especializadas que ofrecen garantías 
suficientes y están legalmente autorizadas para poder ejercer esta actividad. 


<!------------------------------------------------------------------------------------------------->
## El seguro privado

El seguro (privado) es un contrato mediante el cual una de las partes, el asegurador, se obliga, a 
cambio del pago de una prima, a indemnizar a la otra parte, dentro de los límites convenidos, de una 
pérdida o un daño producido por un acontecimiento incierto; o a pagar un capital o una renta, si 
ocurre la eventualidad prevista en el contrato.

-- Ref. Art. 1, Decreto Supremo 1147 del 29/Nov/1963

### Actores {-}

- El asegurado
  - El tomador del seguro
  - El portador del riesgo
  - El beneficiario
- La empresa de seguros
- Las empresas de reaseguros o retrocesiones

## Clasificación según la materia asegurada

1. Seguros de personas

- Destinados a asegurar los riesgos que afecten la vida, la integridad física o la situación 
familiar de las personas.

2. Seguros generales o de daños

- Destinados a cubrir los riesgos que pueden amenazar al patrimonio de las personas o instituciones.

-- Ref. Decreto 1147


### Seguros de personas {-}

- Seguros de vida

- Seguros de salud o asistencia médica

- Seguros de accidentes

- Seguros de natalidad

### Seguros generales o de daños {-}

- Seguro de cosas
- El objeto amenazado es un bien del patrimonio del asegurado
- Ej: incendio, robo, inundación,…

- Seguro de responsabilidad
- El objeto amenazado es el patrimonio global del asegurado
- Ej: responsabilidad civil, responsabilidad médica


## Clasificación según el beneficio

1. Seguros de compensación o de sumas fijas

- El beneficio es fijado de antemano sin referencia a la magnitud del siniestro
- Ej: 50 USD diarios por hospitalización
- Ej: 20,000 USD en caso de muerte.

2. Seguros de indemnización

- Cubren el perjuicio real del siniestro, según las condiciones del contrato
- Ej: incendio de un inmueble.


## Clasificación según la regulación

1. Seguros de vida
- Cubren los riesgos de las personas o garantizan a éstas, dentro o al término de un plazo, 
un capital o una renta periódica

2. Seguros generales (de daños)
- Cubren los riesgos causados por afecciones, pérdidas o daños de la salud, de los bienes o del
patrimonio y fianzas o garantías.

-- Ref. Art. 3, Ley General de Seguros.


## Visita web de la SCVS y JPRF


## Principios básicos del seguro

1. Buena fe
2. Interés asegurable
3. Indemnización
4. Subrogación


### Principio de buena fe {-}

Tanto el asegurador como el asegurado deben actuar con máxima honestidad,
moral y buena fe.

El asegurado debe declarar todas las características del riesgo que se asegura.

El asegurador debe explicar con claridad y detalle las condiciones de la cobertura que ofrece.


### Principio del interés asegurable {-}

El asegurado debe sufrir una pérdida económica si el riesgo asegurado se realiza.

No se puede asegurar legalmente nada que no tenga interés asegurable.

El interés debe ser lícito.

- En seguros de personas, toda persona tiene interés asegurable:
- En su propia vida;
- En la de las personas a quienes pueda reclamar alimentos, y
- En la de aquellas cuya muerte pueda aparejarle un perjuicio económico.
- En los amparos accesorios de gastos que tengan carácter de daño patrimonial, como gastos 
médicos, clínicos, quirúrgicos o farmacéuticos
- Son susceptibles de indemnización y se regulan por las normas relativas a los seguros de daños.

- En seguros de daños puede ser objeto de contrato de seguro todo interés económico en que una
persona tenga en que no se produzca un siniestro.

-- Ref. Decreto 1147

### Principio de indemnización {-}

La indemnización no puede exceder el valor real del interés asegurado ni el monto efectivo del 
prejuicio patrimonial ni el límite de la suma asegurada.

El seguro no puede constituir fuente de enriquecimiento del asegurado.

A opción del asegurador la indemnización es pagadera en dinero mediante la reposición, reparación o
reconstrucción de la cosa asegurada.


En los seguros de personas el valor del interés asegurable no tiene otro límite que el que 
libremente le asignen las partes contratantes.

-- Ref. Decreto 1147

### Principio de subrogación {-}

- El asegurador sustituye al asegurado en el ejercicio de las acciones o derechos que tendría este, 
a fin de recuperar la indemnización.
-- Diccionario MAPFRE de seguros

- El asegurador que haya pagado una indemnización de seguro se subroga, por Ministerio de la Ley, 
hasta el monto de dicha indemnización, en los derechos del asegurado contra terceros responsables
del siniestro.

-- Ref. Decreto 1147

- Consecuencia
  -Bienes recuperables pasan a ser propiedad de la compañía 
  -Ej. carros robados y recuperados.


## Seguro o apuesta?
```{r l3t1, echo = TRUE, results = 'asis', out.width='100%', class.source = 'fold-hide'}
tbd <- as.data.frame(
matrix( c(
    'Respaldo legal estricto',              'Puede ser ilegal',
    'Interés asegurable indispensable',     'Carece de interés asegurable',
    'Máxima buena fe',                      'No necesariamente de buena fe',
    'Nunca es fuente de enriquecimiento',   'Puede ser fuente de enriquecimiento' 
  ),
  nrow = 4, ncol = 2, byrow = TRUE )
)
tbd %>%
  kable(
    label = NA,
    caption = 'Seguros vs Apuestas',
    row.names = FALSE,
    col.names = c( 'Seguros', 'Apuestas' ),
    align = 'll',
    digits = c( 0, 0 ),
    format.args = list( big.mark = ',', decimal.mark = '.', scientific = FALSE ),
    escape = FALSE,
    centering = TRUE, 
    booktabs = TRUE ) %>%
  kable_classic( full_width = FALSE, html_font = "Cambria", position = "center" ) %>%
  scroll_box( width = "100%", height = "300px" )
```

Estas características permiten distinguir claramente las operaciones de seguro de las apuestas 
o la especulación financiera.

## Fuentes del riesgo en seguros

- Número de reclamos: frecuencia
- Costo de los reclamos: severidad
- Período de cobertura
- Período de pago de primas
- Período de pago de siniestros
- Desde la fecha del reclamo hasta el cierre legal.

## Problemas que enfrentan los seguros

Identificamos tres problemas principales:

- Asegurabilidad de riesgos
- Selección adversa (anti-selección)
- Azar moral

### Asegurabilidad de riesgos

Recordemos que el seguro se fundamenta en la compensación o mutualización de riesgos que no siempre
es posible aplicar, y además, el seguro enfrenta algunas limitaciones técnicas. Por lo tanto existen
riesgos que no son siempre asegurables y su transferencia dependerá de la capacidad financiera y 
aversión al riesgo de la compañía de seguros.

### Riesgos asegurables (deseables) {-}

  - Riesgos comparables y de naturaleza homogénea
  - Es necesario que se puedan mutualizar 
    - Para que se cumpla la ley de los grandes números
  - Riesgos medibles 
    - responden a una ley de probabilidad
    - permitan estimar la pérdida máxima
  - Riesgos no potestativos: que no dependen de la voluntad del asegurado
  - Riesgos inciertos
    - Que no hayan ocurrido o que su ocurrencia sea desconocida.
    
    
### Selección adversa

Es un fenómeno causado porque la información del asegurador es incompleta y asimétrica:

- El asegurado es quien conoce mejor el riesgo.

Entonces el seguro atrae con más fuerza a quienes tienen mayor exposición al riesgo y el portafolio 
puede resultar desequilibrado, asegurando demasiados “malos riesgos” que causan el desequilibrio 
financiero

### Medidas contra la selección adversa {-}

Con la finalidad de equilibrar el portafolio el mercado a puesto en práctica algunas medidas:

- Personalización de la prima para asegurados siniestrosos 
  - Ej. bonus malus
- Proceso de selección de asegurados en base a declaración del riesgo
- Potestad de la compañía para rechazar un seguro
- Obligación de asegurar?
- Período de carencia
- Límites de cobertura
- Copago, franquicia, deducible, suma máxima asegurada


### Azar moral

Es el riesgo de que el asegurado se desinterese de prevenir la ocurrencia de siniestros:

- Ej. Seguro automotriz

o se interese en que ocurra el riesgo:

- Ej. Por publicidad

o incremente la frecuencia de reclamos

- Ej. Seguro de salud


### Medidas contra el azar moral {-}

Con el objetivo de incentivar la prevención, el mercado ha desarrollado algunas estrategias:

- Copago y/o deducible
- Obligaciones de prevención previstas en el contrato
- Cobertura máxima
  - Por siniestro
  - Por período
- Bono *no-claims*.


## Primas de seguro: Art. 53 RLGS

- Prima pura o prima de riesgo: es el costo del riesgo
- Prima neta: prima pura más un recargo de seguridad
- Prima de tarifa: prima neta más recargos de operación:
  - gastos de adquisición, 
  - gastos de administración,
  - utilidad razonable
  - otros gastos justificados (legales, inspección, ...)
- Prima comercial: prima de tarifa más impuestos, contribuciones, etc.

### Relación fundamental {-}

$$ P_{tar} = \frac{P}{1-GA-GB-U} $$
$P$: prima pura

$P_{tar}$: prima de tarifa

$GA$: porcentaje de gastos de administración

$GB$: porcentaje de gastos de adquisición (comisiones de *brokers*)

$U$: porcentaje de utilidad esperada por los accionistas 

Los porcentajes se calculan sobre la prima de tarifa.


## Caso Nessie

- Estudio de caso.

<!-- ver web -->
